name: Example deploy workflow

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Installing node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    # Comment out to run the deploy script when you push to the repository.
    #- run: npm run deploy
    #  env:
    #    DXP_OE_SERVER_URL: ${{ secrets.CDCI_STAGING_URL }}
    #    DXP_OE_SERVER_TOKEN: ${{ secrets.CDCI_STAGING_TOKEN }}
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - run: | 
        pwd;
        ls;
        find artifacts/Application/testingapp/script/neptune.Script -type f -name '*.script' -print0 | while IFS= read -r -d '' f; do
        mv -- "$f" "${f%.script}.js"
        # cd artifacts/Application/testingapp/script/neptune.Script
        # rename "s/script$/js/" *.script
        # for file in artifacts/Application/testingapp/script/neptune.Script/*.script; do 
        # mv -- "$file" "${file%.script}.js"

        done
    
      



    - run: npm run test
    env:
       DXP_OE_SERVER_URL: ${{ secrets.CDCI_STAGING_URL }}
       DXP_OE_SERVER_TOKEN: ${{ secrets.CDCI_STAGING_TOKEN }}
